import { WHOVaccine } from "../types/vaccine";

/**
 * WHO Expanded Programme on Immunization (EPI) Schedule — 2024
 *
 * Covers birth → 18 months. Each entry is a single dose of a single vaccine.
 * Common aliases include Indian brand names, shorthand, and generic names.
 *
 * Reference:
 *   https://www.who.int/teams/immunization-vaccines-and-biologicals/policies/who-recommendations-for-routine-immunization---summary-tables
 *
 * DISCLAIMER: VaccineGuard is NOT a medical tool. Always consult a
 * healthcare professional for vaccination advice.
 */
export const WHO_SCHEDULE: WHOVaccine[] = [
    // =========================================================================
    // BIRTH (0 weeks)
    // =========================================================================
    {
        id: "bcg-1",
        vaccineName: "BCG",
        commonAliases: ["Bacillus Calmette-Guérin", "BCG Vaccine", "Tubervac", "BCG SSI"],
        recommendedAgeWeeks: 0,
        recommendedAgeLabel: "Birth",
        doses: 1,
        doseNumber: 1,
        disease: "Tuberculosis",
        isMandatory: true,
        notes: "Single intradermal dose at birth or as early as possible. Leaves a characteristic scar on the upper left arm.",
    },
    {
        id: "hepb-1",
        vaccineName: "Hepatitis B",
        commonAliases: ["HepB-BD", "Hep B Birth Dose", "Engerix-B", "Shanvac-B", "Revac-B"],
        recommendedAgeWeeks: 0,
        recommendedAgeLabel: "Birth",
        doses: 4,
        doseNumber: 1,
        disease: "Hepatitis B",
        isMandatory: true,
        notes: "Birth dose should be given within 24 hours of birth to prevent perinatal transmission.",
    },
    {
        id: "opv-0",
        vaccineName: "OPV-0",
        commonAliases: ["OPV Zero Dose", "Oral Polio Vaccine", "Polio Drops", "bOPV-0"],
        recommendedAgeWeeks: 0,
        recommendedAgeLabel: "Birth",
        doses: 5,
        doseNumber: 1,
        disease: "Poliomyelitis",
        isMandatory: true,
        notes: "Zero dose of oral polio vaccine given at birth. Does not count toward the primary series in some schedules.",
    },

    // =========================================================================
    // 6 WEEKS
    // =========================================================================
    {
        id: "dtwp-1",
        vaccineName: "DTwP-1",
        commonAliases: ["DTP-1", "DTaP-1", "Triple Antigen", "Pentavac", "Easyfive", "Infanrix", "Boostrix"],
        recommendedAgeWeeks: 6,
        recommendedAgeLabel: "6 weeks",
        doses: 4,
        doseNumber: 1,
        disease: "Diphtheria, Tetanus, Pertussis",
        isMandatory: true,
        notes: "First dose of the primary 3-dose DTP series. Often given as part of a pentavalent combo (DTP-HepB-Hib).",
    },
    {
        id: "opv-1",
        vaccineName: "OPV-1",
        commonAliases: ["Oral Polio Vaccine Dose 1", "Polio Drops", "bOPV-1"],
        recommendedAgeWeeks: 6,
        recommendedAgeLabel: "6 weeks",
        doses: 5,
        doseNumber: 2,
        disease: "Poliomyelitis",
        isMandatory: true,
        notes: "First primary series dose of oral polio vaccine.",
    },
    {
        id: "ipv-1",
        vaccineName: "IPV-1",
        commonAliases: ["Inactivated Polio Vaccine", "Salk Vaccine", "IMOVAX Polio", "Poliovac"],
        recommendedAgeWeeks: 6,
        recommendedAgeLabel: "6 weeks",
        doses: 3,
        doseNumber: 1,
        disease: "Poliomyelitis",
        isMandatory: true,
        notes: "At least one dose of IPV is recommended by WHO alongside OPV in the primary series.",
    },
    {
        id: "hib-1",
        vaccineName: "Hib-1",
        commonAliases: ["Haemophilus influenzae type b", "PedvaxHIB", "ActHIB", "Hiberix"],
        recommendedAgeWeeks: 6,
        recommendedAgeLabel: "6 weeks",
        doses: 4,
        doseNumber: 1,
        disease: "Haemophilus influenzae type b infections (meningitis, pneumonia)",
        isMandatory: true,
        notes: "Often combined in pentavalent vaccine (DTP-HepB-Hib).",
    },
    {
        id: "pcv-1",
        vaccineName: "PCV-1",
        commonAliases: ["Pneumococcal Conjugate Vaccine", "Prevnar 13", "PCV13", "Synflorix", "PCV10"],
        recommendedAgeWeeks: 6,
        recommendedAgeLabel: "6 weeks",
        doses: 4,
        doseNumber: 1,
        disease: "Pneumococcal disease (pneumonia, meningitis)",
        isMandatory: true,
        notes: "First dose of the pneumococcal conjugate series. PCV10 or PCV13 depending on country programme.",
    },
    {
        id: "rota-1",
        vaccineName: "Rotavirus-1",
        commonAliases: ["Rotavirus Vaccine", "Rotavac", "Rotarix", "RotaTeq", "Rotasiil"],
        recommendedAgeWeeks: 6,
        recommendedAgeLabel: "6 weeks",
        doses: 3,
        doseNumber: 1,
        disease: "Rotavirus gastroenteritis",
        isMandatory: true,
        notes: "Oral vaccine. Rotarix is 2-dose; RotaTeq/Rotavac/Rotasiil is 3-dose. First dose by 15 weeks of age.",
    },
    {
        id: "hepb-2",
        vaccineName: "Hepatitis B-2",
        commonAliases: ["HepB-2", "Engerix-B", "Shanvac-B", "Revac-B"],
        recommendedAgeWeeks: 6,
        recommendedAgeLabel: "6 weeks",
        doses: 4,
        doseNumber: 2,
        disease: "Hepatitis B",
        isMandatory: true,
        notes: "Second dose; often given as part of pentavalent combination vaccine.",
    },

    // =========================================================================
    // 10 WEEKS
    // =========================================================================
    {
        id: "dtwp-2",
        vaccineName: "DTwP-2",
        commonAliases: ["DTP-2", "DTaP-2", "Triple Antigen", "Pentavac", "Easyfive", "Infanrix"],
        recommendedAgeWeeks: 10,
        recommendedAgeLabel: "10 weeks",
        doses: 4,
        doseNumber: 2,
        disease: "Diphtheria, Tetanus, Pertussis",
        isMandatory: true,
        notes: "Second dose of the DTP primary series. Minimum 4-week interval from dose 1.",
    },
    {
        id: "opv-2",
        vaccineName: "OPV-2",
        commonAliases: ["Oral Polio Vaccine Dose 2", "Polio Drops", "bOPV-2"],
        recommendedAgeWeeks: 10,
        recommendedAgeLabel: "10 weeks",
        doses: 5,
        doseNumber: 3,
        disease: "Poliomyelitis",
        isMandatory: true,
        notes: "Second primary series dose of OPV.",
    },
    {
        id: "ipv-2",
        vaccineName: "IPV-2",
        commonAliases: ["Inactivated Polio Vaccine Dose 2", "Salk Vaccine", "IMOVAX Polio"],
        recommendedAgeWeeks: 10,
        recommendedAgeLabel: "10 weeks",
        doses: 3,
        doseNumber: 2,
        disease: "Poliomyelitis",
        isMandatory: true,
        notes: "Second IPV dose. Some countries give only one IPV dose in primary series; check national schedule.",
    },
    {
        id: "hib-2",
        vaccineName: "Hib-2",
        commonAliases: ["Haemophilus influenzae type b Dose 2", "PedvaxHIB", "ActHIB"],
        recommendedAgeWeeks: 10,
        recommendedAgeLabel: "10 weeks",
        doses: 4,
        doseNumber: 2,
        disease: "Haemophilus influenzae type b infections (meningitis, pneumonia)",
        isMandatory: true,
        notes: "Second dose; often combined in pentavalent vaccine.",
    },
    {
        id: "pcv-2",
        vaccineName: "PCV-2",
        commonAliases: ["Pneumococcal Conjugate Vaccine Dose 2", "Prevnar 13", "Synflorix"],
        recommendedAgeWeeks: 10,
        recommendedAgeLabel: "10 weeks",
        doses: 4,
        doseNumber: 2,
        disease: "Pneumococcal disease (pneumonia, meningitis)",
        isMandatory: true,
        notes: "Second dose of the PCV series.",
    },
    {
        id: "rota-2",
        vaccineName: "Rotavirus-2",
        commonAliases: ["Rotavirus Vaccine Dose 2", "Rotavac", "Rotarix", "RotaTeq", "Rotasiil"],
        recommendedAgeWeeks: 10,
        recommendedAgeLabel: "10 weeks",
        doses: 3,
        doseNumber: 2,
        disease: "Rotavirus gastroenteritis",
        isMandatory: true,
        notes: "Second dose. Final dose for Rotarix (2-dose schedule).",
    },

    // =========================================================================
    // 14 WEEKS
    // =========================================================================
    {
        id: "dtwp-3",
        vaccineName: "DTwP-3",
        commonAliases: ["DTP-3", "DTaP-3", "Triple Antigen", "Pentavac", "Easyfive", "Infanrix"],
        recommendedAgeWeeks: 14,
        recommendedAgeLabel: "14 weeks",
        doses: 4,
        doseNumber: 3,
        disease: "Diphtheria, Tetanus, Pertussis",
        isMandatory: true,
        notes: "Third and final dose of the DTP primary series.",
    },
    {
        id: "opv-3",
        vaccineName: "OPV-3",
        commonAliases: ["Oral Polio Vaccine Dose 3", "Polio Drops", "bOPV-3"],
        recommendedAgeWeeks: 14,
        recommendedAgeLabel: "14 weeks",
        doses: 5,
        doseNumber: 4,
        disease: "Poliomyelitis",
        isMandatory: true,
        notes: "Third primary series dose of OPV.",
    },
    {
        id: "ipv-3",
        vaccineName: "IPV-3",
        commonAliases: ["Inactivated Polio Vaccine Dose 3", "Salk Vaccine", "IMOVAX Polio"],
        recommendedAgeWeeks: 14,
        recommendedAgeLabel: "14 weeks",
        doses: 3,
        doseNumber: 3,
        disease: "Poliomyelitis",
        isMandatory: true,
        notes: "Third IPV dose. Completes the primary IPV series for countries using a 3-dose schedule.",
    },
    {
        id: "hib-3",
        vaccineName: "Hib-3",
        commonAliases: ["Haemophilus influenzae type b Dose 3", "PedvaxHIB", "ActHIB"],
        recommendedAgeWeeks: 14,
        recommendedAgeLabel: "14 weeks",
        doses: 4,
        doseNumber: 3,
        disease: "Haemophilus influenzae type b infections (meningitis, pneumonia)",
        isMandatory: true,
        notes: "Third dose; completes the Hib primary series.",
    },
    {
        id: "pcv-3",
        vaccineName: "PCV-3",
        commonAliases: ["Pneumococcal Conjugate Vaccine Dose 3", "Prevnar 13", "Synflorix"],
        recommendedAgeWeeks: 14,
        recommendedAgeLabel: "14 weeks",
        doses: 4,
        doseNumber: 3,
        disease: "Pneumococcal disease (pneumonia, meningitis)",
        isMandatory: true,
        notes: "Third dose of the PCV primary series.",
    },
    {
        id: "rota-3",
        vaccineName: "Rotavirus-3",
        commonAliases: ["Rotavirus Vaccine Dose 3", "RotaTeq", "Rotavac", "Rotasiil"],
        recommendedAgeWeeks: 14,
        recommendedAgeLabel: "14 weeks",
        doses: 3,
        doseNumber: 3,
        disease: "Rotavirus gastroenteritis",
        isMandatory: true,
        notes: "Third and final dose for RotaTeq/Rotavac/Rotasiil. Not needed if using Rotarix (2-dose). Must be given by 32 weeks of age.",
    },

    // =========================================================================
    // 9 MONTHS (~39 weeks)
    // =========================================================================
    {
        id: "measles-1",
        vaccineName: "Measles-1",
        commonAliases: ["MCV1", "Measles Vaccine", "MR Vaccine", "M-Vac", "Rouvax"],
        recommendedAgeWeeks: 39,
        recommendedAgeLabel: "9 months",
        doses: 2,
        doseNumber: 1,
        disease: "Measles",
        isMandatory: true,
        notes: "First dose of measles-containing vaccine. Given as measles-only or MR (measles-rubella). MMR may be used if MR is unavailable.",
    },
    {
        id: "yf-1",
        vaccineName: "Yellow Fever",
        commonAliases: ["YF Vaccine", "Stamaril", "YF-Vax", "17D Vaccine"],
        recommendedAgeWeeks: 39,
        recommendedAgeLabel: "9 months",
        doses: 1,
        doseNumber: 1,
        disease: "Yellow Fever",
        isMandatory: false,
        notes: "Recommended only in endemic/at-risk regions (parts of Africa and South America). Single dose provides lifelong immunity.",
    },
    {
        id: "vita-1",
        vaccineName: "Vitamin A-1",
        commonAliases: ["Vitamin A Supplementation", "VAS", "Retinol"],
        recommendedAgeWeeks: 39,
        recommendedAgeLabel: "9 months",
        doses: 2,
        doseNumber: 1,
        disease: "Vitamin A deficiency (immune support, reduces measles mortality)",
        isMandatory: false,
        notes: "100,000 IU oral dose at 9 months. Not a vaccine but included in the WHO EPI contact schedule. Given alongside measles vaccine.",
    },

    // =========================================================================
    // 12 MONTHS (~52 weeks)
    // =========================================================================
    {
        id: "hepa-1",
        vaccineName: "Hepatitis A-1",
        commonAliases: ["HepA-1", "Havrix", "Avaxim", "Biovac-A", "Healive"],
        recommendedAgeWeeks: 52,
        recommendedAgeLabel: "12 months",
        doses: 2,
        doseNumber: 1,
        disease: "Hepatitis A",
        isMandatory: false,
        notes: "First dose of hepatitis A vaccine. Recommended by WHO in countries with intermediate/high endemicity. Two-dose schedule.",
    },
    {
        id: "var-1",
        vaccineName: "Varicella-1",
        commonAliases: ["Chickenpox Vaccine", "Varilrix", "Varivax", "VZV Vaccine"],
        recommendedAgeWeeks: 52,
        recommendedAgeLabel: "12 months",
        doses: 2,
        doseNumber: 1,
        disease: "Varicella (Chickenpox)",
        isMandatory: false,
        notes: "First dose at 12 months. WHO recommends only if ≥80% coverage is achievable in the national programme. Two-dose schedule preferred.",
    },
    {
        id: "pcv-booster",
        vaccineName: "PCV Booster",
        commonAliases: ["Pneumococcal Booster", "Prevnar 13 Booster", "PCV13-B", "Synflorix Booster"],
        recommendedAgeWeeks: 52,
        recommendedAgeLabel: "12 months",
        doses: 4,
        doseNumber: 4,
        disease: "Pneumococcal disease (pneumonia, meningitis)",
        isMandatory: true,
        notes: "Booster dose of pneumococcal conjugate vaccine. Given at 12 months in the 3p+1 schedule (3 primary + 1 booster).",
    },

    // =========================================================================
    // 15 MONTHS (~65 weeks)
    // =========================================================================
    {
        id: "mmr-1",
        vaccineName: "MMR-1",
        commonAliases: ["MMR Vaccine", "Measles-Mumps-Rubella", "Priorix", "M-M-R II", "Tresivac"],
        recommendedAgeWeeks: 65,
        recommendedAgeLabel: "15 months",
        doses: 2,
        doseNumber: 1,
        disease: "Measles, Mumps, Rubella",
        isMandatory: true,
        notes: "First MMR dose. If measles-only or MR was given at 9 months, this serves as the second measles-containing dose with added mumps and rubella coverage.",
    },
    {
        id: "var-1-alt",
        vaccineName: "Varicella-1 (if not given at 12m)",
        commonAliases: ["Chickenpox Vaccine", "Varilrix", "Varivax", "VZV Vaccine"],
        recommendedAgeWeeks: 65,
        recommendedAgeLabel: "15 months",
        doses: 2,
        doseNumber: 1,
        disease: "Varicella (Chickenpox)",
        isMandatory: false,
        notes: "Catch-up Varicella dose at 15 months if not administered at 12 months. Can be given as MMRV combination.",
    },

    // =========================================================================
    // 16-18 MONTHS (~72 weeks)
    // =========================================================================
    {
        id: "dtwp-booster",
        vaccineName: "DTwP Booster",
        commonAliases: ["DTP Booster-1", "DTaP Booster", "Triple Antigen Booster", "Boostrix", "Pentavac Booster"],
        recommendedAgeWeeks: 72,
        recommendedAgeLabel: "16-18 months",
        doses: 4,
        doseNumber: 4,
        disease: "Diphtheria, Tetanus, Pertussis",
        isMandatory: true,
        notes: "First booster dose of DTP. Given 6-12 months after the third primary dose to reinforce immunity.",
    },
    {
        id: "opv-booster",
        vaccineName: "OPV Booster",
        commonAliases: ["OPV Booster-1", "Oral Polio Booster", "Polio Drops Booster", "bOPV Booster"],
        recommendedAgeWeeks: 72,
        recommendedAgeLabel: "16-18 months",
        doses: 5,
        doseNumber: 5,
        disease: "Poliomyelitis",
        isMandatory: true,
        notes: "Booster dose of OPV to maintain mucosal immunity against poliovirus.",
    },
    {
        id: "hib-booster",
        vaccineName: "Hib Booster",
        commonAliases: ["Hib Booster-1", "Haemophilus influenzae Booster", "PedvaxHIB Booster", "ActHIB Booster"],
        recommendedAgeWeeks: 72,
        recommendedAgeLabel: "16-18 months",
        doses: 4,
        doseNumber: 4,
        disease: "Haemophilus influenzae type b infections (meningitis, pneumonia)",
        isMandatory: true,
        notes: "Booster dose to ensure long-term protection. Given 6-12 months after completing the primary 3-dose series.",
    },

    // =========================================================================
    // 18 MONTHS (~78 weeks)
    // =========================================================================
    {
        id: "hepa-2",
        vaccineName: "Hepatitis A-2",
        commonAliases: ["HepA-2", "Havrix Dose 2", "Avaxim Booster", "Biovac-A Dose 2"],
        recommendedAgeWeeks: 78,
        recommendedAgeLabel: "18 months",
        doses: 2,
        doseNumber: 2,
        disease: "Hepatitis A",
        isMandatory: false,
        notes: "Second and final dose of Hepatitis A. Given 6 months after the first dose for long-term protection.",
    },
    {
        id: "mmr-2",
        vaccineName: "MMR-2",
        commonAliases: ["MMR Dose 2", "Measles-Mumps-Rubella Booster", "Priorix", "M-M-R II", "Tresivac"],
        recommendedAgeWeeks: 78,
        recommendedAgeLabel: "18 months",
        doses: 2,
        doseNumber: 2,
        disease: "Measles, Mumps, Rubella",
        isMandatory: true,
        notes: "Second dose of MMR to ensure seroconversion. At least 4 weeks after the first MMR dose.",
    },
];
